#!/usr/bin/env bash
# bash script

DOMAIN_NAME=$1
SUBDOMAIN=$2
FILE=file.txt

{
    dig www."$1" | grep -A1 'ANSWER SECTION:'
    dig lb-01."$1" | grep -A1 'ANSWER SECTION:'
    dig web-01."$1" | grep -A1 'ANSWER SECTION:'
    dig web-02."$1" | grep -A1 'ANSWER SECTION:'
} >> $FILE

if [ -z "$DOMAIN_NAME"  ]
then
    echo The subdomain "" is a "" record and points to  ""
fi

func2 () {
      if [ -z "$SUBDOMAIN" ]
      then
      awk '/www/ {print "The subdomain www is a "$4" record and points to "$5;}' $FILE
      awk '/lb-01/ {print "The subdomain lb-01 is a "$4" record and points to "$5;}' $FILE
      awk '/web-01/ {print "The subdomain web-01 is a "$4" record and points to "$5;}' $FILE
      awk '/web-02/ {print "The subdomain web-02 is a "$4" record and points to "$5;}' $FILE
      else
      awk -v my_var="$SUBDOMAIN" "/$SUBDOMAIN/"'{print "The subdomain "my_var" is a "$4" record and points to "$5;}' $FILE
      fi
      return 0
}

func2 "$DOMAIN_NAME" "$SUBDOMAIN"



echo "" > $FILE
