#!/usr/bin/env bash
# Install and configure nginx on a new server.
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx start
