#!/usr/bin/env bash
# Install and configure nginx on a new server.
sudo apt-get -y update && sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
