#!/usr/bin/env bash
# Install and configure nginx on a new server
sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
sed -i 's|location /|location /redirect_me/|' /etc/nginx/sites-available/default
sed -i -r '/# as directory, then fall back to displaying a 404./a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
service nginx restart
