#!/usr/bin/env bash
# Install and configure nginx on a new server.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
printf "Ceci n'est pas une page\n\n" | sudo tee /var/www/html/404.html
sed -i '\%root /var/www/html;% a error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
