#!/usr/bin/env bash
# configure web-02 to be identical to web-01 by configuring nginx so its http
# response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html

file=/etc/nginx/sites-available/default

sed -i 's|location /|location /redirect_me/|' $file
sed -i -r '/# as directory, then fall back to displaying a 404./a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' $file

printf "Ceci n'est pas une page\n\n" | sudo tee /usr/share/nginx/html/404.html
sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;|' $file
sudo service nginx restart

sed -i '38a \ \tlocation / {\n\tadd_header X-Served-By $hostname;\n\t}\n' $file
sudo service nginx restart
