#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server
apt-get -y update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.5

apt-get -y update
apt-get install -y haproxy=1.5.\*

echo "
frontend http
    bind *:80
    mode http                                                                      default_backend web-backend
backend web-backend
    balance roundrobin
    server 829-web-01 35.227.56.7:80 check
    server 829-web-02 35.231.96.229:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
