#!/usr/bin/env bash
# Generates a MySQL dump of all databases and creates a compressed archive out of it.
DATE=$(date +%d-%m-%Y)
if [ $# -eq 1 ]; then
    mysqldump -u root -p"$1" --all-databases > backup.sql
    tar -cvzf "$DATE".tar.gz backup.sql
fi
