#!/usr/bin/env bash
# Script to fix my Nginx server that isn't listening on port 80.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
