#!/usr/bin/env bash
# Bash script that displays to infinity and beyond and i am inv
TRUE=true
trap "echo I am invincible!!!" SIGTERM
while [ $TRUE ]; do
    echo "To infinity and beyond"
    sleep 2
done
