#!/usr/bin/env bash
# Displays time for 12 hours and 59 min
hours=0
minutes=1
while [ $hours -le 12 ];
do
	echo "Hour: $hours"
	while [ $minutes -lt 60 ];
	do
		echo $minutes
		((minutes++))
	done
	((hours++))
	minutes=1
done
