#!/usr/bin/env bash
# Configure container to run nginx as nginx user. Nginx must be listening on all active IPs on port 8080. Cannot use apt-get remove
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
